-- Run this in Supabase SQL Editor

-- 1. Runs Table
create table public.runs (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  status text, -- RUNNING, STOPPED, FAILED, COMPLETED
  config jsonb,
  engine_version text,
  symbols jsonb,
  result jsonb
);

-- 2. Logs Table (Realtime enabled)
create table public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  run_id uuid references public.runs(id),
  timestamp timestamp with time zone,
  message text,
  level text,
  data jsonb
);

-- 3. Trades Table
create table public.trades (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  run_id uuid references public.runs(id),
  symbol text,
  side text,
  entry_price numeric,
  exit_price numeric,
  quantity numeric,
  pnl numeric,
  reason text,
  entry_time timestamp with time zone,
  exit_time timestamp with time zone
);

-- 4. Commands Table (C2)
create table public.commands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  command text, -- START_RUN, STOP_RUN
  payload jsonb,
  status text default 'PENDING', -- PENDING, PROCESSING, COMPLETED, FAILED
  result jsonb
);

-- 5. Enable Realtime
alter publication supabase_realtime add table logs;
alter publication supabase_realtime add table runs;
alter publication supabase_realtime add table commands;
