-- Create market_data table for storing candle/tick data
create table if not exists public.market_data (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  symbol text not null,
  price numeric,
  volume numeric,
  timestamp timestamp with time zone,
  run_id uuid references public.runs(id)
);

-- Enable Realtime for market_data
alter publication supabase_realtime add table market_data;
