"""
Strategy Interface.
"""
from abc import ABC, abstractmethod
from typing import List, Optional, Dict, Any, Union
from datetime import datetime
from dataclasses import dataclass

from ..common.types import Tick, OrderSide, OrderType

@dataclass
class Intent:
    """
    Strategy intent to Buy/Sell.
    Strategies emit this, Engine executes it.
    """
    strategy_name: str
    symbol: str
    side: OrderSide
    quantity: float # or None if 'use_max'
    price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reason: str = ""

@dataclass
class FillEvent:
    symbol: str
    side: OrderSide
    quantity: float
    price: float
    timestamp: datetime
    fee: float = 0.0

class Strategy(ABC):
    """
    Base Strategy Class.
    """
    def __init__(self, name: str, config: Dict[str, Any]):
        self.name = name
        self.config = config

    @abstractmethod
    def generate_signals(self, tick: Tick) -> List[Intent]:
        """
        Called on every market tick.
        Should return a list of Intents (Buy/Sell) or empty list.
        """
        pass

    @abstractmethod
    def on_fill(self, fill: FillEvent):
        """
        Called when an order generated by this strategy is filled.
        """
        pass

    @abstractmethod
    def on_bar_close(self, bar: Any):
        """
        Called on candle close (if engine supports bar events).
        """
        pass
